// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGducg5A2isvv33v-KWCYis6wN82DctG4',
    appId: '1:815048812615:web:0d7adb66710293aaf12962',
    messagingSenderId: '815048812615',
    projectId: 'my-car-rental-try',
    authDomain: 'my-car-rental-try.firebaseapp.com',
    storageBucket: 'my-car-rental-try.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrRBQtSedcmBg2QN8QpMy2IiK6yP2YRR0',
    appId: '1:815048812615:android:725a8dffb6358523f12962',
    messagingSenderId: '815048812615',
    projectId: 'my-car-rental-try',
    storageBucket: 'my-car-rental-try.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3tsE8TaT5mA3R4rWeXqZFs5sJaYyIqbQ',
    appId: '1:815048812615:ios:7f21ecf5eb6b83b8f12962',
    messagingSenderId: '815048812615',
    projectId: 'my-car-rental-try',
    storageBucket: 'my-car-rental-try.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3tsE8TaT5mA3R4rWeXqZFs5sJaYyIqbQ',
    appId: '1:815048812615:ios:7f21ecf5eb6b83b8f12962',
    messagingSenderId: '815048812615',
    projectId: 'my-car-rental-try',
    storageBucket: 'my-car-rental-try.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGducg5A2isvv33v-KWCYis6wN82DctG4',
    appId: '1:815048812615:web:df952af9e4c2da42f12962',
    messagingSenderId: '815048812615',
    projectId: 'my-car-rental-try',
    authDomain: 'my-car-rental-try.firebaseapp.com',
    storageBucket: 'my-car-rental-try.firebasestorage.app',
  );
}
